### ISSUE TITLE
ask to roll anothe time the dice only if needed

### ISSUE THREAD

**Issue by valerio-vaccaro** [n3s1us/bitcoin-seed-phrase-composer-with-dice#3]
Procedure at https://en.bitcoin.se/articles/create-your-own-wallet-seed-using-regular-dice penalize subset with empty cells, i suggest to roll dice another time only if:
- the cell is empty for last roll,
- the subset is totally empty for roll before last one.

**Comment by pidark** [comment]
What exactly do you mean by "penalize" the subset with empty cells?

One of the next improvements I have in mind is to make it compatible with 2 (a coin) 4 8 16 sided dice which do not give selection of empty cells. But with a 6-sided die I couldn't find a better solution than this. And I preferred to use the 6-sided dice because it is more common.

So do you suggest displaying a warning to start the word selection round all over again when, for example, after two dice rolls, 6 already comes up twice (because is selected a table with all cells empty)?

**Comment by valerio-vaccaro** [comment]
Roll the dice 5 times instead of 1 when needed.
I suggest to roll dice another time (and only one) ONLY IF:

- we are il last roll and we finish in a  empty cell,
- we are not in last roll and the subset identified is totally empty.

Or you can create one number between 0-2047 and use this as a index for the mnemonic word.

**Comment by pidark** [comment]
In this way the words would no longer have the same probability of extraction.

See this: https://en.wikipedia.org/wiki/Monty_Hall_problem

**Comment by valerio-vaccaro** [comment]
ok
