### ISSUE TITLE
Slight issue with word probabilities

### ISSUE THREAD

**Issue by sarpulhu** [n3s1us/bitcoin-seed-phrase-composer-with-dice#4]
It appears first roll 4,5,6 has a smaller list of words than 1,2,3 roll first. This would mean that not all words have the same probability.  When groups are ignored the ignored group has to be distributed evenly.  You might be able to modify it to match my method but would involve ignoring 5 and 6 value rolls.

**Comment by pidark** [comment]
This should perhaps be better specified in the usage rules, when the data selects an empty box the message "Selection empty, throw your dice again to make a round from scratch so that every word has the same probabilities!" appears. The rule is that if you select an empty square the dice must be re-rolled for that word again this causes the probabilities of the empty squares to be redistributed evenly. So don't just raise the last 2 dice but all 5 dice.

This problem only occurs with the 6-sided dice configuration.

What solutions do you propose? (which is not clear to me)

**Comment by sarpulhu** [comment]
I'm not good at explaining. For example the words on the right (4-6) for first digit is smaller than (1-3). So words on the left will show up more often because the ones on the right are sometimes thrown away. If you are throwing away you have to make sure it doesn't create unequal group sizes.  
A fix would be to use something like my diceware table to divide up in fourths. First divide list in half to 1024. Then use 1-4 to break the groups down. There would be no empty or uneven sides but 5 and 6 have to be re-rolled. This way all words have same odds.

**Comment by sarpulhu** [comment]
The more I think of it the more I'm unsure now. I'll remove this if you want.

**Comment by pidark** [comment]
Let's see if I can illustrate how there is equal probability in all words.

Imagine it like this in the first two large right and left quadrants there are the same number of cells, only on the right some cells are empty but they are the same number.

So all cells have the same probability of being extracted.

If an empty cell is extracted, the process has to restart from zero therefore the probability of empty cells is equally distributed on all the other cells (even the empty ones but until a full cell is extracted the process repeats itself).

So it is important that if a quadrant of empty cells is selected, not only the last die must be re-rolled, but all the dice of that round to extract the word.
